### ISSUE TITLE
MatchError for bv_concat/4pr while trying to print a formula

### ISSUE THREAD

**Issue by daniel-raffler** [uuverifiers/princess#14]
Hello,
this one may be related to #13 as it can often be seen for very similar problems. The crash happens while trying to print a formula: 
```
Exception in thread "main" scala.MatchError: bv_concat/4pr (of class ap.theories.bitvectors.ModuloArithmetic$BVConcat$)
	at ap.parser.SMTLineariser$.ap$parser$SMTLineariser$$theoryFun2Identifier(SMTLineariser.scala:773)
	at ap.parser.SMTLineariser.ap$parser$SMTLineariser$$fun2Identifier(SMTLineariser.scala:880)
	at ap.parser.SMTLineariser$AbsyPrinter$.preVisit(SMTLineariser.scala:1192)
	at ap.parser.SMTLineariser$AbsyPrinter$.preVisit(SMTLineariser.scala:1038)
	at ap.parser.CollectingVisitor.visitWithoutResult(InputAbsyVisitor.scala:195)
	at ap.parser.SMTLineariser$AbsyPrinter$.apply(SMTLineariser.scala:1041)
	at ap.parser.SMTLineariser.printFormula(SMTLineariser.scala:959)
	at ap.parser.SMTLineariser$.apply(SMTLineariser.scala:572)
	at ap.parser.SMTLineariser$.apply(SMTLineariser.scala:550)
	at ap.parser.SMTLineariser$.$anonfun$asString$1(SMTLineariser.scala:601)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at ap.DialogUtil$.captureOutput(DialogMain.scala:68)
	at ap.DialogUtil$.asString(DialogMain.scala:64)
	at ap.parser.SMTLineariser$.asString(SMTLineariser.scala:601)
	at ap.parser.SMTLineariser$.asString(SMTLineariser.scala:596)
	at ap.parser.SMTLineariser.asString(SMTLineariser.scala)
	at org.sosy_lab.java_smt.solvers.princess.PrincessEnvironment$1.appendTo0(PrincessEnvironment.java:442)
	at org.sosy_lab.java_smt.solvers.princess.PrincessEnvironment$1.appendTo(PrincessEnvironment.java:380)
	at org.sosy_lab.common.Appenders.appendTo(Appenders.java:73)
	at org.sosy_lab.common.Appenders.toString(Appenders.java:186)
	at org.sosy_lab.common.Appenders$AbstractAppender.toString(Appenders.java:262)
	at org.sosy_lab.cpachecker.util.predicates.smt.FormulaManagerView.dumpArbitraryFormula(FormulaManagerView.java:1959)
	at org.sosy_lab.cpachecker.core.algorithm.bmc.AbstractBMCAlgorithm.boundedModelCheck(AbstractBMCAlgorithm.java:710)
	at org.sosy_lab.cpachecker.core.algorithm.bmc.AbstractBMCAlgorithm.boundedModelCheck(AbstractBMCAlgorithm.java:686)
	at org.sosy_lab.cpachecker.core.algorithm.bmc.BMCAlgorithm.boundedModelCheck(BMCAlgorithm.java:158)
	at org.sosy_lab.cpachecker.core.algorithm.bmc.AbstractBMCAlgorithm.run(AbstractBMCAlgorithm.java:454)
	at org.sosy_lab.cpachecker.core.algorithm.bmc.BMCAlgorithm.run(BMCAlgorithm.java:130)
	at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:489)
	at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:357)
	at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:171)
```
The formula that triggers the crash is very large and probably won't be of much use. However, I'll keep looking and will update the issue once I've found something smaller.

**Comment by pruemmer** [comment]
This was a missing case in the pretty-printer, should work now!
